services:
  database:
    container_name: database
    image: "mysql:8.4.0"
    restart: always
    environment:
      MYSQL_DATABASE: hris
      MYSQL_ROOT_PASSWORD: dev1234
      MYSQL_TCP_PORT: 3308
    volumes:
      - db-data:/data
    ports:
      - 3308:3308
    expose:
      - 3308

  backend:
    container_name: backend
    build:  ./backend
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - database

  
volumes:
  db-data: