services:
  database:
    container_name: database
    image: "mysql:8.4.0"
    restart: always
    volumes:
      - db-data:/data
    environment:
      - MYSQL_DATABASE=hris
      - MYSQL_ROOT_PASSWORD=dev1234
      - MYSQL_TCP_PORT=3308
    ports:
      - 3308:3308
    expose:
      - 3308
      
  # backend:
  #   container_name: backend
  #   depends_on:
  #     - database
  #   restart: always
  #   build:  ./backend
  #   ports:
  #     - "3000:3000"
  #   expose:
  #     - 3000
      


  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - "4000:4000"
  #   expose:
  #     - 4000
  #   depends_on:
  #     - backend

  
volumes:
  db-data: